

app:
  name: "kelbi-web"
  image: "ghcr.io/invasor-de-fronteiras/kelbi-web:sha256-10c104255c176bd186aae0f5800920a7a6f7b583c3845b0f45c4488842f36dba"
  replicas: 1

config:
  env: kelbi-web-secrets
  port: 3000
network:
  expose: true
  domain: "admin.arcamh.com"

resources:
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
